Upgrade glibc to 2.34
Note the --force-overwrite flag is required.

Without adding the override flag, this was the error;
ERROR: glibc-2.25-r0: trying to overwrite etc/nsswitch.conf owned by alpine-baselayout-data-3.4.0-r0.